name: Deploy fibonacci-docker
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t dennishenderson/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true dennishenderson/react-test npm test
 
      - run: docker build -t dennishenderson/fibonacci-client ./client
      - run: docker build -t dennishenderson/fibonacci-nginx ./nginx
      - run: docker build -t dennishenderson/fibonacci-server ./server
      - run: docker build -t dennishenderson/fibonacci-worker ./worker
 
      - run: docker push dennishenderson/fibonacci-client
      - run: docker push dennishenderson/fibonacci-nginx
      - run: docker push dennishenderson/fibonacci-server
      - run: docker push dennishenderson/fibonacci-worker
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: fibonacci-docker
          environment_name: fibonaccidocker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-513660770506
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip